// src/app/features/admin/components/problem-form/problem-form.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, FormArray, Validators } from '@angular/forms';
import { Router, ActivatedRoute } from '@angular/router';
import { ProblemService } from '../../../../services/problem.service';
import { TagService } from '../../../../services/tag.service';
import { Problem, Tag, ProblemExample } from '../../../../models/problem.model';

@Component({
  selector: 'app-problem-form',
  template: `
    <div class="container-fluid py-4">
      <div class="card">
        <div class="card-header">
          <h3>{{ isEditMode ? 'Редактирование задачи' : 'Создание задачи' }}</h3>
        </div>
        <div class="card-body">
          <form [formGroup]="problemForm" (ngSubmit)="onSubmit()">
            <div class="mb-3">
              <label for="title" class="form-label">Название</label>
              <input
                type="text"
                class="form-control"
                id="title"
                formControlName="title"
                [ngClass]="{'is-invalid': submitted && f['title'].errors}"
              >
              <div *ngIf="submitted && f['title'].errors" class="invalid-feedback">
                <div *ngIf="f['title'].errors['required']">Название обязательно</div>
              </div>
            </div>

            <div class="mb-3">
              <label for="description" class="form-label">Описание</label>
              <textarea
                class="form-control"
                id="description"
                rows="5"
                formControlName="description"
                [ngClass]="{'is-invalid': submitted && f['description'].errors}"
              ></textarea>
              <div *ngIf="submitted && f['description'].errors" class="invalid-feedback">
                <div *ngIf="f['description'].errors['required']">Описание обязательно</div>
              </div>
            </div>

            <div class="mb-3">
              <label for="difficulty" class="form-label">Сложность</label>
              <select
                class="form-select"
                id="difficulty"
                formControlName="difficulty"
                [ngClass]="{'is-invalid': submitted && f['difficulty'].errors}"
              >
                <option value="">Выберите сложность</option>
                <option value="easy">Легкая</option>
                <option value="medium">Средняя</option>
                <option value="hard">Сложная</option>
              </select>
              <div *ngIf="submitted && f['difficulty'].errors" class="invalid-feedback">
                <div *ngIf="f['difficulty'].errors['required']">Сложность обязательна</div>
              </div>
            </div>

            <div class="mb-3">
              <label class="form-label">Теги</label>
              <div class="d-flex flex-wrap gap-2">
                <div *ngFor="let tag of availableTags" class="form-check">
                  <input
                    class="form-check-input"
                    type="checkbox"
                    [id]="'tag-' + tag.id"
                    [value]="tag.id"
                    [checked]="isTagSelected(tag.id)"
                    (change)="onTagChange($event, tag.id)"
                  >
                  <label class="form-check-label" [for]="'tag-' + tag.id">
                    {{ tag.name }}
                  </label>
                </div>
              </div>
            </div>

            <div class="mb-3">
              <label class="form-label">Примеры</label>
              <div formArrayName="examples">
                <div *ngFor="let example of examples.controls; let i = index" [formGroupName]="i" class="card mb-3">
                  <div class="card-body">
                    <div class="mb-3">
                      <label [for]="'input-' + i" class="form-label">Входные данные</label>
                      <textarea
                        [id]="'input-' + i"
                        class="form-control"
                        formControlName="input"
                        rows="2"
                      ></textarea>
                    </div>
                    <div class="mb-3">
                      <label [for]="'output-' + i" class="form-label">Выходные данные</label>
                      <textarea
                        [id]="'output-' + i"
                        class="form-control"
                        formControlName="output"
                        rows="2"
                      ></textarea>
                    </div>
                    <div class="mb-3">
                      <label [for]="'explanation-' + i" class="form-label">Объяснение</label>
                      <textarea
                        [id]="'explanation-' + i"
                        class="form-control"
                        formControlName="explanation"
                        rows="2"
                      ></textarea>
                    </div>
                    <button type="button" class="btn btn-danger" (click)="removeExample(i)">
                      Удалить пример
                    </button>
                  </div>
                </div>
              </div>
              <button type="button" class="btn btn-secondary" (click)="addExample()">
                Добавить пример
              </button>
            </div>

            <div class="d-flex gap-2">
              <button type="submit" class="btn btn-primary" [disabled]="loading">
                {{ loading ? 'Сохранение...' : 'Сохранить' }}
              </button>
              <button type="button" class="btn btn-secondary" (click)="cancel()">
                Отмена
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  `,
  styles: []
})
export class ProblemFormComponent implements OnInit {
  problemForm: FormGroup;
  availableTags: Tag[] = [];
  loading = false;
  submitted = false;
  isEditMode = false;
  problemId?: number;

  constructor(
    private formBuilder: FormBuilder,
    private route: ActivatedRoute,
    private router: Router,
    private problemService: ProblemService,
    private tagService: TagService
  ) {
    this.createForm();
  }

  ngOnInit(): void {
    this.loadTags();
    this.problemId = Number(this.route.snapshot.paramMap.get('id'));
    this.isEditMode = !!this.problemId;

    if (this.isEditMode) {
      this.loadProblem();
    }
  }

  get f() {
    return this.problemForm.controls;
  }

  get examples() {
    return this.f['examples'] as FormArray;
  }

  private createForm(): void {
    this.problemForm = this.formBuilder.group({
      title: ['', Validators.required],
      description: ['', Validators.required],
      difficulty: ['', Validators.required],
      tagIds: [[]],
      examples: this.formBuilder.array([])
    });
  }

  private loadTags(): void {
    this.tagService.getTags().subscribe(tags => {
      this.availableTags = tags;
    });
  }

  private loadProblem(): void {
    if (!this.problemId) return;

    this.loading = true;
    this.problemService.getProblem(this.problemId).subscribe({
      next: (problem) => {
        this.problemForm.patchValue({
          title: problem.title,
          description: problem.description,
          difficulty: problem.difficulty,
          tagIds: problem.tags.map(t => t.id)
        });

        problem.examples.forEach(example => {
          this.examples.push(this.createExampleFormGroup(example));
        });

        this.loading = false;
      },
      error: () => {
        this.loading = false;
        this.router.navigate(['/admin/problems']);
      }
    });
  }

  addExample(): void {
    this.examples.push(this.createExampleFormGroup());
  }

  removeExample(index: number): void {
    this.examples.removeAt(index);
  }

  private createExampleFormGroup(example?: ProblemExample): FormGroup {
    return this.formBuilder.group({
      input: [example?.input || '', Validators.required],
      output: [example?.output || '', Validators.required],
      explanation: [example?.explanation || '']
    });
  }

  isTagSelected(tagId: number): boolean {
    return this.f['tagIds'].value.includes(tagId);
  }

  onTagChange(event: Event, tagId: number): void {
    const checkbox = event.target as HTMLInputElement;
    const tagIds = this.f['tagIds'].value as number[];

    if (checkbox.checked) {
      this.f['tagIds'].setValue([...tagIds, tagId]);
    } else {
      this.f['tagIds'].setValue(tagIds.filter(id => id !== tagId));
    }
  }

  cancel(): void {
    this.router.navigate(['/admin/problems']);
  }

  onSubmit(): void {
    this.submitted = true;

    if (this.problemForm.invalid) {
      return;
    }

    this.loading = true;
    const formData = this.problemForm.value;

    if (this.isEditMode && this.problemId) {
      this.problemService.updateProblem(this.problemId, formData).subscribe({
        next: () => this.router.navigate(['/admin/problems']),
        error: () => this.loading = false
      });
    } else {
      this.problemService.createProblem(formData).subscribe({
        next: () => this.router.navigate(['/admin/problems']),
        error: () => this.loading = false
      });
    }
  }
}

// src/components/ProblemForm.tsx
import React, { useState, useEffect } from 'react';
import { Problem, Tag, Example } from '../types';

interface ProblemFormProps {
  problem?: Problem;
  tags: Tag[];
  onSubmit: (problem: Omit<Problem, 'id'>) => Promise<void>;
  onCancel: () => void;
}

const ProblemForm: React.FC<ProblemFormProps> = ({ problem, tags, onSubmit, onCancel }) => {
  const [formData, setFormData] = useState<Omit<Problem, 'id'>>({
    title: '',
    description: '',
    difficulty: 'Easy',
    tags: [],
    examples: [],
  });

  useEffect(() => {
    if (problem) {
      setFormData({
        title: problem.title,
        description: problem.description,
        difficulty: problem.difficulty,
        tags: problem.tags,
        examples: problem.examples,
      });
    }
  }, [problem]);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    await onSubmit(formData);
  };

  const addExample = () => {
    setFormData(prev => ({
      ...prev,
      examples: [
        ...prev.examples,
        { input: '', output: '', explanation: '' }
      ]
    }));
  };

  const removeExample = (index: number) => {
    setFormData(prev => ({
      ...prev,
      examples: prev.examples.filter((_, i) => i !== index)
    }));
  };

  const updateExample = (index: number, field: keyof Example, value: string) => {
    setFormData(prev => ({
      ...prev,
      examples: prev.examples.map((example, i) => 
        i === index ? { ...example, [field]: value } : example
      )
    }));
  };

  return (
    <form onSubmit={handleSubmit} className="container">
      <div className="card">
        <div className="card-body">
          <h2 className="card-title mb-4">
            {problem ? 'Редактирование задачи' : 'Создание новой задачи'}
          </h2>

          <div className="mb-3">
            <label className="form-label">Название</label>
            <input
              type="text"
              className="form-control"
              value={formData.title}
              onChange={(e) => setFormData(prev => ({ ...prev, title: e.target.value }))}
              required
            />
          </div>

          <div className="mb-3">
            <label className="form-label">Описание</label>
            <textarea
              className="form-control"
              rows={5}
              value={formData.description}
              onChange={(e) => setFormData(prev => ({ ...prev, description: e.target.value }))}
              required
            />
          </div>

          <div className="mb-3">
            <label className="form-label">Сложность</label>
            <select
              className="form-select"
              value={formData.difficulty}
              onChange={(e) => setFormData(prev => ({ ...prev, difficulty: e.target.value }))}
            >
              <option value="Easy">Легкая</option>
              <option value="Medium">Средняя</option>
              <option value="Hard">Сложная</option>
            </select>
          </div>

          <div className="mb-3">
            <label className="form-label">Теги</label>
            <div className="d-flex flex-wrap gap-2">
              {tags.map(tag => (
                <div key={tag.id} className="form-check">
                  <input
                    type="checkbox"
                    className="form-check-input"
                    id={`tag-${tag.id}`}
                    checked={formData.tags.some(t => t.id === tag.id)}
                    onChange={(e) => {
                      if (e.target.checked) {
                        setFormData(prev => ({
                          ...prev,
                          tags: [...prev.tags, tag]
                        }));
                      } else {
                        setFormData(prev => ({
                          ...prev,
                          tags: prev.tags.filter(t => t.id !== tag.id)
                        }));
                      }
                    }}
                  />
                  <label className="form-check-label" htmlFor={`tag-${tag.id}`}>
                    {tag.name}
                  </label>
                </div>
              ))}
            </div>
          </div>

          <div className="mb-3">
            <div className="d-flex justify-content-between align-items-center">
              <label className="form-label">Примеры</label>
              <button
                type="button"
                className="btn btn-outline-primary btn-sm"
                onClick={addExample}
              >
                Добавить пример
              </button>
            </div>
            {formData.examples.map((example, index) => (
              <div key={index} className="card mb-2">
                <div className="card-body">
                  <div className="d-flex justify-content-between align-items-center mb-2">
                    <h6 className="card-subtitle mb-2">Пример {index + 1}</h6>
                    <button
                      type="button"
                      className="btn btn-outline-danger btn-sm"
                      onClick={() => removeExample(index)}
                    >
                      Удалить
                    </button>
                  </div>
                  <div className="mb-2">
                    <label className="form-label">Входные данные</label>
                    <input
                      type="text"
                      className="form-control"
                      value={example.input}
                      onChange={(e) => updateExample(index, 'input', e.target.value)}
                    />
                  </div>
                  <div className="mb-2">
                    <label className="form-label">Выходные данные</label>
                    <input
                      type="text"
                      className="form-control"
                      value={example.output}
                      onChange={(e) => updateExample(index, 'output', e.target.value)}
                    />
                  </div>
                  <div className="mb-2">
                    <label className="form-label">Объяснение</label>
                    <textarea
                      className="form-control"
                      value={example.explanation}
                      onChange={(e) => updateExample(index, 'explanation', e.target.value)}
                    />
                  </div>
                </div>
              </div>
            ))}
          </div>

          <div className="d-flex gap-2">
            <button type="submit" className="btn btn-primary">
              {problem ? 'Сохранить' : 'Создать'}
            </button>
            <button type="button" className="btn btn-secondary" onClick={onCancel}>
              Отмена
            </button>
          </div>
        </div>
      </div>
    </form>
  );
};

export default ProblemForm;
